### ISSUE TITLE
Reproduce.py gave error "Cell excection timed out", even though local run of notebook worked fine.

### ISSUE THREAD

**Issue by taaursland** [econ-ark/QuARK#19]
Some of the cells, do take a couple of minutes. In particular the simulation of seven types.

Edit: changing number of types to two, Python does not time out.

**Comment by MridulS** [comment]
thanks for the feedback I have added an option for `--timeout` in the script which can be manually increased if required. The default now is 600s for each cell rather than 30s.

example of using timeout
` python reproduce.py --timeout 30 --local notebooks/LifeCycleModelExample-Problems-And-Solutions.ipynb`

**Comment by MridulS** [comment]
Can you pull in the new script by doing
`
$ git pull origin master
`
Can you test this locally and let me know?

**Comment by taaursland** [comment]
Hi, running the command above, I get the error "Container <string w/ number and letters> is not running. I have not fixed the Docker, so running with sudu command first.
